# Generated by Django 4.2.5 on 2023-09-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_image_file", models.ImageField(upload_to="images/")),
                ("avg_hex_value", models.CharField(max_length=50)),
            ],
        ),
    ]
