# Generated by Django 4.2.5 on 2023-09-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imageProcessor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/thumbnails")),
                ("center_hex", models.CharField(max_length=50)),
                ("rgb_val", models.CharField(max_length=50)),
                ("color_name", models.CharField(max_length=50)),
            ],
        ),
    ]
